

export const mainRoutes = [
  {
    route: '/',
    name: 'App.home',
    layout: 'App_body',
    template: 'Landing_page',
    importStr: '/imports/ui/pages/landing-page/landing-page.js'
  },
  {
    route: '/my-account',
    name: 'User.home',
    layout: 'App_body',
    template: 'User_home',
    importStr: '/imports/ui/pages/user-home/user-home.js',
  },
  {
    route: '/menu',
    name: 'Menu.show',
    layout: 'App_body',
    template: 'Menu_page',
    importStr: '/imports/ui/pages/menu-page/menu-page.js',
  },
  {
    route: '/market',
    name: 'Market',
    layout: 'App_body',
    template: 'Market_page',
    importStr: '/imports/ui/pages/market-page/market-page.js',
  },
  {
    route: '/about-us',
    name: 'About.us',
    layout: 'App_body',
    template: 'About_page',
    importStr: '/imports/ui/pages/about-page/about-page.js',
  },
  {
    route: '/confirmation',
    name: 'Confirmation',
    layout: 'App_body',
    template: 'Confirmation',
    importStr: '/imports/ui/pages/confirmation-page/confirmation-page.js',
  },
  {
    route: '/settings',
    name: 'Account.settings',
    layout: 'App_body',
    template: 'Account_page',
    importStr: '/imports/ui/pages/account-page/account-page.js',
  },
  {
    route: '/subscribe',
    name: 'Subscribe',
    layout: 'App_body',
    template: 'Subscribe',
    importStr: '/imports/ui/pages/subscribe/subscribe.js',
  },
  {
    route: '/subscriptions',
    name: 'My.subscriptions',
    layout: 'App_body',
    template: 'My_Subscriptions',
    importStr: '/imports/ui/pages/my-subscriptions/my-subscriptions.js',
  },
  {
    route: '/orders',
    name: 'My.orders',
    layout: 'App_body',
    template: 'My_Orders',
    importStr: '/imports/ui/pages/my-orders/my-orders.js',
  },
  {
    route: '/gifts',
    name: 'Gifts',
    layout: 'App_body',
    template: 'Gift_Cards',
    importStr: '/imports/ui/pages/gift-cards/gift-cards.js',
  },
  {
    route: '/blog',
    name: 'Blog.roll',
    layout: 'App_body',
    template: 'Blog_page',
    importStr: '/imports/ui/pages/blog-page/blog-page.js',
  },
  {
    route: '/menu/:_id',
    name: 'Item.show',
    layout: 'App_body',
    template: 'Item_detail',
    importStr: '/imports/ui/pages/item-detail/item-detail.js',
  },
  {
    route: '/support',
    name: 'Support',
    layout: 'App_body',
    template: 'Support_page',
    importStr: '/imports/ui/pages/support/support.js',
  },
  {
    route: '/checkout',
    name: 'Checkout',
    layout: 'App_body',
    template: 'Checkout_page',
    importStr: '/imports/ui/pages/checkout-page/checkout-page.js',
  },
  {
    route: '/success',
    name: 'Success',
    layout: 'App_body',
    template: 'Success_page',
    importStr: '/imports/ui/pages/success/success.js',
  },
  {
    route: '/redeem',
    name: 'redeem',
    layout: 'App_body',
    template: 'Success_page', // 2 success pages?
    importStr: '/imports/ui/pages/success/success.js',
  },
  {
    route: '/jobs',
    name: 'Jobs',
    layout: 'App_body',
    template: 'Jobs',
    importStr: '/imports/ui/pages/jobs/jobs.js',
  },
  {
    route: '/media',
    name: 'Media',
    layout: 'App_body',
    template: 'Media',
    importStr: '/imports/ui/pages/media/media.js',
  },
  {
    route: '/test',
    name: 'Test',
    layout: 'App_body',
    template: 'Test',
    importStr: '/imports/ui/pages/test/test.js',
  },
  {
    route: '/equinox',
    name: 'Equinox.join',
    layout: 'App_body',
    template: 'Equinox_join',
    importStr: '/imports/ui/pages/equinox-join/equinox-join.js',
  },
  {
    route: '/deanstreet',
    name: 'DeanStreet',
    layout: 'App_body',
    template: 'DeanStreet',
    importStr: '/imports/ui/pages/dean-street/dean-street.js',
  },
];

export const mainNotFound = {
  layout: 'App_body',
  template: 'App_notFound',
};

export const adminRoutes = [
  {
    route: '/',
    name: 'Main.admin',
    layout: 'Admin_layout',
    template: 'Main_admin',
    importStr: '/imports/ui/pages/main-admin/main-admin.js',
  },
  {
    route: '/menu',
    name: 'Menu.admin',
    layout: 'Admin_layout',
    template: 'Menu_admin',
    importStr: '/imports/ui/pages/menu-admin/menu-admin.js',
  },
  {
    route: '/orders',
    name: 'Orders.admin',
    layout: 'Admin_layout',
    template: 'Orders_admin',
    importStr: '/imports/ui/pages/orders-admin/orders-admin.js',
  },
  {
    route: '/customers',
    name: 'Customers.admin',
    layout: 'Admin_layout',
    template: 'Customers_admin',
    importStr: '/imports/ui/pages/customers-admin/customers-admin.js',
  },
  {
    route: '/customers/:_id',
    name: 'Customer.detail',
    layout: 'Admin_layout',
    template: 'Customer_detail',
    importStr: '/imports/ui/pages/customer-detail/customer-detail.js',
  },
  {
    route: '/subscribers',
    name: 'Subscribers.admin',
    layout: 'Admin_layout',
    template: 'Subscribers_admin',
    importStr: '/imports/ui/pages/subscribers-admin/subscribers-admin.js',
  },
  {
    route: '/promos',
    name: 'Promos.admin',
    layout: 'Admin_layout',
    template: 'Promos_admin',
    importStr: '/imports/ui/pages/promos-admin/promos-admin.js',
  },
  {
    route: '/specs',
    name: 'Wiki.Index',
    layout: 'Admin_layout',
    template: 'Wiki_index',
    importStr: '/imports/ui/wiki/index.js',
  },
];
