export const PackSchemas = {
	omnivore: {
		4: {
			name: 'Omnivore 4-Pack',
      price: 63,
			schema: {
				protein: 1,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 0,
        total: 4,
			},
		},
		6: {
			name: 'Omnivore 6-Pack',
      price: 87.37,
			schema: {
				protein: 2,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 6,
			},
		},
		8: {
			name: 'Omnivore 8-Pack',
      price: 120.53,
			schema: {
				protein: 3,
				vegetable: 2,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 8,
			},
		},
		10: {
			name: 'Omnivore 10-Pack',
      price: 152.63,
			schema: {
				protein: 4,
				vegetable: 2,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 10,
			},
		},
		12: {
			name: 'Omnivore 12-Pack',
      price: 185.79,
			schema: {
				protein: 5,
				vegetable: 3,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 12,
			},
		},
	},

	paleo: {
		4: {
			name: 'Paleo 4-Pack',
      price: 63,
			schema: {
				protein: 1,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 0,
        total: 4,
			},
		},
		6: {
			name: 'Paleo 6-Pack',
      price: 88.42,
			schema: {
				protein: 2,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 6,
			},
		},
		8: {
			name: 'Paleo 8-Pack',
      price: 118.42,
			schema: {
				protein: 3,
				vegetable: 2,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 8,
			},
		},
		10: {
			name: 'Paleo 10-Pack',
      price: 151.58,
			schema: {
				protein: 4,
				vegetable: 2,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 10,
			},
		},
		12: {
			name: 'Paleo 12-Pack',
      price: 178.42,
			schema: {
				protein: 5,
				vegetable: 3,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 12,
			},
		},
	},

	pescetarian: {
		4: {
			name: 'Pescetarian 4-Pack',
      price: 64.05,
			schema: {
				protein: 1,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 0,
        total: 4,
			},
		},
		6: {
			name: 'Pescetarian 6-Pack',
      price: 88.42,
			schema: {
				protein: 2,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 6,
			},
		},
		8: {
			name: 'Pescetarian 8-Pack',
      price: 118.95,
			schema: {
				protein: 2,
				vegetable: 2,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 8,
			},
		},
		10: {
			name: 'Pescetarian 10-Pack',
      price: 152.63,
			schema: {
				protein: 3,
				vegetable: 3,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 10,
			},
		},
		12: {
			name: 'Pescetarian 12-Pack',
      price: 183.16,
			schema: {
				protein: 3,
				vegetable: 4,
				grain: 3,
				salad: 1,
				soup: 1,
        total: 12,
			},
		},
	},

	vegetarian: {
		4: {
			name: 'Vegetarian 4-Pack',
      price: 60.90,
			schema: {
				protein: 1,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 0,
        total: 4,
			},
		},
		6: {
			name: 'Vegetarian 6-Pack',
      price: 85.26,
			schema: {
				protein: 1,
				vegetable: 2,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 6,
			},
		},
		8: {
			name: 'Vegetarian 8-Pack',
      price: 117.89,
			schema: {
				protein: 2,
				vegetable: 3,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 8,
			},
		},
		10: {
			name: 'Vegetarian 10-Pack',
      price: 149.47,
			schema: {
				protein: 3,
				vegetable: 3,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 10,
			},
		},
		12: {
			name: 'Vegetarian 12-Pack',
      price: 180,
			schema: {
				protein: 3,
				vegetable: 4,
				grain: 3,
				salad: 1,
				soup: 1,
        total: 12,
			},
		},
	},

	vegan: {
		4: {
			name: 'Vegan 4-Pack',
      price: 60.90,
			schema: {
				protein: 1,
				vegetable: 1,
				grain: 1,
				salad: 1,
				soup: 0,
        total: 4,
			},
		},
		6: {
			name: 'Vegan 6-Pack',
      price: 85.26,
			schema: {
				protein: 1,
				vegetable: 2,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 6,
			},
		},
		8: {
			name: 'Vegan 8-Pack',
      price: 117.89,
			schema: {
				protein: 2,
				vegetable: 3,
				grain: 1,
				salad: 1,
				soup: 1,
        total: 8,
			},
		},
		10: {
			name: 'Vegan 10-Pack',
      price: 149.47,
			schema: {
				protein: 3,
				vegetable: 3,
				grain: 2,
				salad: 1,
				soup: 1,
        total: 10,
			},
		},
		12: {
			name: 'Vegan 12-Pack',
      price: 180,
			schema: {
				protein: 3,
				vegetable: 4,
				grain: 3,
				salad: 1,
				soup: 1,
        total: 12,
			},
		},
	},
}